[project]
name = "app"
slug = "myapp1"
description = "Order Data Analysis using Preswald"
version = "0.1.0"
entrypoint = "hello.py"

[sources]
list_of_orders = { type = "csv", path = "data/List of Orders.csv" }
